version: "3.2"

volumes:
    db:

services:
    db:
        image: mysql:5.7.28
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: mysql
            MYSQL_PASSWORD: mysql
            MYSQL_DATABASE: recipe_db
        ports:
            - "8081:3306"
        volumes:
            - type: volume
              source: db
              target: /var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:5.1.1
        ports:
            - 8082:80
        environment:
            PMA_USER: root
            PMA_PASSWORD: root
            PMA_HOST: db
